config/routes.rb
SeiyaApp::Application.routes.draw do
  resources :users 
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :shiftdates, only: [:create, :destroy]
  root 'static_pages#home'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
	belongs_to :user
	default_scope -> { order('created_at DESC') }
	validates :content, presence: true, length: { maximum: 140 }
	validates :user_id, presence: true
end

app/models/shiftdate.rb
class Shiftdate < ActiveRecord::Base
	belongs_to :user
	default_scope -> { order('created_at DESC') }
	validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :microposts, dependent: :destroy
	has_many :shiftdates, dependent: :destroy

	before_save {self.email = email.downcase}
	before_create :create_remember_token

	validates :name, presence: true, length: {maximum: 50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: {case_sensitive: false}

	has_secure_password
	validates :password, length: {minimum: 6}

	def User.new_remember_token
    	SecureRandom.urlsafe_base64
  	end

  	def User.encrypt(token)
    	Digest::SHA1.hexdigest(token.to_s)
  	end

  	def feed(users)
  		Micropost.where(user_id: users)
  	end

  	private

  		def create_remember_token
  			self.remember_token = User.encrypt(User.new_remember_token)
  		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :signed_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy

	def create
		@micropost = current_user.microposts.build(micropost_params)#has_many,belong_toの関連づけから使えるようになるメソッド
		if @micropost.save
			flash[:success] = "Micropost created"
			redirect_to root_url
		else
			@feed_items = []
			render 'static_pages/home'
		end
	end

	def destroy
		@micropost.destroy
    	redirect_to root_url
	end

	private
		def micropost_params
			params.require(:micropost).permit(:content)#contentしか編集させない
		end 

		def correct_user
			@micropost = current_user.microposts.find_by(id: params[:id])
      		redirect_to root_url if @micropost.nil?
      	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password]) 
			sign_in user
			redirect_back_or user
		else
			flash.now[:error] = "Invalide email/password combination"
			render 'new'
		end	
	end

	def destroy
		sign_out
		redirect_to root_url
	end
end

app/controllers/shiftdates_controller.rb
class ShiftdatesController < ApplicationController
  before_action :signed_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy

  def create
  	@shiftdate = current_user.shiftdates.build(shiftdate_params)
    if @shiftdate.save
      flash[:success] = "Shift dates created!"
      redirect_to current_user
    else
      render 'static_pages/home'
    end
  end

  def destroy
  	@shiftdate.destroy
    redirect_to current_user
  end

  private

    def shiftdate_params
      params.require(:shiftdate).permit(:date)
    end

    def correct_user
      @shiftdate = current_user.shiftdates.find_by(id: params[:id])
      redirect_to root_url if @shiftdate.nil?
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@micropost = current_user.microposts.build if signed_in?
  	@shiftdate = current_user.shiftdates.build if signed_in?
  	if signed_in?
  		user = current_user
  		users = User.find_all_by_company(user.company)
  		@feed_items = current_user.feed(users).paginate(page: params[:page])
  	end
  end

  def help
  end

  def about
  end

  def contact
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	require 'rubygems'
	require 'active_support/all'

  before_action :signed_in_user, only: [:index, :edit, :update, :destroy]#url直接うったときのため
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user,     only: :destroy
  
  def index
  	user = current_user
  	@users = User.paginate(page: params[:page]).find_all_by_company(user.company)
  end

  def show
  	if current_user.admin?
  		d = Date.today
  		d_start = d.beginning_of_month
  		d_end = d.end_of_month
		@next_month_array = (d_start..d_end).to_a


  		user = current_user
  		@users = User.paginate(page: params[:page]).find_all_by_company(user.company)

  		@user = User.find(params[:id])
  		@shiftdates = @user.shiftdates.paginate(page: params[:page])
  		@shiftdate = current_user.shiftdates.build if signed_in?
  	else
  		@user = User.find(params[:id])
  		@shiftdates = @user.shiftdates.paginate(page: params[:page])
  		@shiftdate = current_user.shiftdates.build if signed_in?
  	end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
    	sign_in @user
    	flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update_attributes(user_params)
  		flash[:success] = "Profile updated"
  		redirect_to @user
  	else
  		render 'edit'
  	end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:company, :name, :email, :password,
                                   :password_confirmation)
    end

    def correct_user
    	@user = User.find(params[:id])
    	redirect_to(root_path) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end 
 end

app/helpers/application_helper.rb
module ApplicationHelper
	#ページごとの完全なタイトルを渡す
	def full_title(page_title)
		base_title = "SeiyaApp";
		if page_title.empty?
			"#{base_title}"
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

	def signed_in?
		!current_user.nil?
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		remember_token = User.encrypt(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
	end


	def current_user?(user)
		user == current_user
	end


	def sign_out
		self.current_user = nil
		cookies.delete(:remember_token)
	end

	def redirect_back_or(default)
		redirect_to (session[:return_to] || default)
		session.delete(:return_to)
	end

	def store_location
		session[:return_to] = request.url
	end

	def signed_in_user
    	unless signed_in?
    		store_location
    		redirect_to signin_url, notice: "Please sign in."
    	end
    end


end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<a href="http://railstutorial.jp/">参考ページ</a>
	</small>
	<nav>
		<ul>
			<li><%= link_to "About Me", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
			<li><a href="http://news.railstutorial.jp/">News</a></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<div class="container">
				<%= link_to "Seiya App", '#', id: "logo"%>
			<nav>
				<ul class="nav pull-right">
					<li><%= link_to "Home", root_path %></li>
					<li><%= link_to "Help", help_path %></li>
					<% if signed_in? %>
            			<li><%= link_to "Users", users_path %></li>
            			<li id="fat-menu" class="dropdown">
              				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
              				<ul class="dropdown-menu">
                				<li><%= link_to "My Shift", current_user %></li>
                				<li><%= link_to "Settings", edit_user_path(current_user) %></li>
                				<li class="divider"></li>
                				<li>
                  					<%= link_to "Sign out", signout_path, method: "delete" %>
                				</li>
              				</ul>
            			</li>
            		<% else %>
						<li><%= link_to "Sign in", signin_path%></li>
					<% end %>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if It IE9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
  	<% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
	<%= yield %>
	<%= render 'layouts/footer' %>
	<%= debug(params) if Rails.env.developement? %>
  </div>
</body>
</html>

app/views/microposts/_micropost.html.erb
<li>
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
  </span>
  <% if current_user?(micropost.user) %>
    <%= link_to "delete", micropost, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: micropost.content %>
  <% end %>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %><!--micropostControllerでcreateした時saveできないと@feed_itemsになにも入らず壊れる-->
	<ol class="microposts">
		<%= render partial: 'shared/feed_item', collection: @feed_items %>
	</ol>
	<%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>"><!--なんでfeed_itemをつかうのか、feed_itemってなに-->
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  <span class="user">
    <%= link_to feed_item.user.name, feed_item.user %>
  </span>
  <span class="content"><%= feed_item.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
  </span>
  <% if current_user?(feed_item.user) %>
    <%= link_to "delete", feed_item, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: feed_item.content %>
  <% end %>
</li>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<div class="field">
		<%= f.text_area :content, placeholder: "Conpose new maicropost..." %>
	</div>
	<%= f.submit "Post", class: "btn btn-large btn-primary" %><!--fがmicropostオブジェクトでsubmitしたらmicropostControllerのcreateメソッドに-->
<% end %>

app/views/shared/_shiftdate_form.html.erb
<%= form_for(@shiftdate) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<div class="field">
		<%= f.date_field :date %></br>
	</div>
	<%= f.submit "Post", class: "btn btn-large btn-primary" %><!--fがmicropostオブジェクトでsubmitしたらmicropostControllerのcreateメソッドに-->
<% end %>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>" >
	<%= gravatar_for current_user, size: 52 %>
</a>
<h1>
	<%= current_user.name %>
</h1>
<span>
	<%= link_to "私のプロフィールを見る" , current_user %>
</span>
<span>
	<%= pluralize(current_user.microposts.count, "micropost") %>
</span>

app/views/shiftdates/_shiftdate.html.erb
<li>
  <span class="content"><%= shiftdate.date %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(shiftdate.created_at) %> ago.
  </span>
  <% if current_user?(shiftdate.user) %>
    <%= link_to "delete", shiftdate, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: shiftdate.date %>
  <% end %>
</li>

app/views/static_pages/about.html.erb
<% provide(:title, 'About us') %>
<h1>About me</h1>

<p>
	これは私に関するページです。
	<br></br>
	<a href="http://flightattendant.boo.jp">ブログ</a>
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contct</h1>
	<p>
		Contact Ruby on Rails Tutorial at the
  <a href="http://railstutorial.jp/contact">contact page</a>.

  	</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% if signed_in? %>
	<div class="row">
		<aside class="span4">
			<section>
				<%= render 'shared/user_info' %>
			</section>
			<section>
				<%= render 'shared/micropost_form' %>
			</section>
		</aside>
		<div class="span8">
			<h3>Micropost Feed</h3>
			<%= render 'shared/feed' %>
		</div>
	</div>
<% else %>
<div class="center hero-unit">
  <h1>SeiyaApp</h1>
	<h2>
	  これはhomeページです。
	  <a href="http://flightattendant.boo.jp">ブログ</a>
	  <br>SeiyaApp<br>
	</h2>
  <%= link_to "Sign up Now", signup_path, class: "btn btn-large btn-primary" %>
</div>
<!--<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>-->
<% end %>

app/views/static_pages/shift.html.erb
<%= provide(:tittle, @user.name) %>
<div class="row">
	<asaide>
		<section class="span4">
			<h1>
			<%= gravatar_for @user %>
			<%= @user.company %>
			<%= @user.name %>
			</h1>
		</section>
	</aside>
	<div class="span8">
    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>

app/views/users/_user.html.erb
<% if current_user.admin? %>

	<tr>
		<th>
  			<!--<%= gravatar_for user, size: 52 %>-->
  			<%= link_to user.name, user %>
  		</th>
  		<% @next_month_array.each do |date| %>
  			<td align="center" width="20px"><% user.shiftdates.each do |shift_date| %>
  					<% if shift_date["date"] == date %>
  						<%= "出" %>
  					<% end %>
  				<% end %>
  			</td>
  		<% end %>
	</tr>
	
<% else %>
	<li>
  	<%= gravatar_for user, size: 52 %>
  	<%= link_to user.name, user %>
  	<% if current_user.admin? && !current_user?(user) %>
    	| <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  	<% end %>
	</li>
<% end %>

app/views/users/_user_index.html.erb
<% @users.each do |user| %>
    <li>
      <%= gravatar_for user, size: 52 %>
      <%= link_to user.name, user %>
      <% if current_user.admin? && !current_user?(user) %>
          | <%= link_to "delete", user, method: :delete,
                        data: { confirm: "You sure?" } %>
      <% end %>
    </li>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :company %>
      <%= f.text_field :company %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Company members') %>
<h1>Company members</h1>

<%= will_paginate %>

<ul class="users">
  <%= render 'user_index' %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
    	<%= render 'shared/error_messages', object: f.object %>

      <%= f.label :company %>
      <%= f.text_field :company %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= provide(:tittle, @user.name) %>
<% if current_user.admin? %>
	<h1>Company shifts</h1>

	<%= will_paginate %>

	<ul class="users">
		<table class="table_01">
			<tr>
		     <th class="big" align="center"><%= "#{@next_month_array[0].month}月" %></th>
			<% @next_month_array.each do |d| %>
				<td align="center"><%= "#{d.day}日" %></td>
			<% end %>
			</tr>
  			<%= render @users %>
  		</table>
	</ul>

	<%= will_paginate %>
<% else %>
<div class="row">
	<aside>
		<section class="span4">
			<h1>
			<%= gravatar_for @user %>
			<%= @user.company %>
			<%= @user.name %>
			</h1>
			<section>
				<%= render 'shared/shiftdate_form' %>
			</section>
		</section>
	</aside>
	<div class="span8">
    <% if @user.shiftdates.any? %>
      <h3>Shift Dates (<%= @user.shiftdates.count %>)</h3>
      <ol class="microposts">
        <%= render @shiftdates %>
      </ol>
      <%= will_paginate @shiftdates %>
    <% end %>
  	</div>
</div>
<% end %>